Add PHPStan, lint and composer audit to CI
CoverGenius/xcover-php pull request #13
Opened 2023-06-19 07:31 UTC by sf-cg

In the github actions CI we've added:

* Lint Check
*  PHPStan check (and added the dependency for it to composer)
*  Composer audit check

On top of this, I've run PHPStan locally and cleaned up the issues it has initially shown.

2023-06-20 09:11 UTC, girishl-cg reviewed
@sf-cg The audit, lint, phpstan and tests has to be separated out  I think so you can see them individually.

2023-07-18 05:28 UTC, sf-cg commented
I've updated so that Lint, Composer Scans, Static Analysis and Tests run separately.

2023-07-21 01:30 UTC, girishl-cg requested changes

2023-07-21 01:30 UTC, girishl-cg commented on .github/workflows/composer.yml
> +          php-version: 8.2
This should be a ${{ matrix.php-version }}

2023-07-21 01:30 UTC, girishl-cg commented on .github/workflows/lint.yml
> +          php-version: 8.2
same should be a ${{ matrix.php-version }}

2023-07-21 01:30 UTC, girishl-cg commented on .github/workflows/static.yml
> +          php-version: 8.2
shd be a ${{ matrix.php-version }}

2023-07-21 01:48 UTC, girishl-cg approved these changes

2023-07-21 03:11 UTC, merged